Document: libilbc
Title: Debian libilbc Manual
Author: <insert document author here>
Abstract: This manual describes what libilbc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libilbc/libilbc.sgml.gz

Format: postscript
Files: /usr/share/doc/libilbc/libilbc.ps.gz

Format: text
Files: /usr/share/doc/libilbc/libilbc.text.gz

Format: HTML
Index: /usr/share/doc/libilbc/html/index.html
Files: /usr/share/doc/libilbc/html/*.html
